services:
  - type: web
    name: karanka-deriv-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5
    envVars:
      - key: SECRET_KEY
        generateValue: true
